nodeLinker: node-modules

enableGlobalCache: false
enableMirror: false

packageExtensions:
  "@tanstack/react-query-devtools@*":
    dependencies:
      csstype: "*"
  autoprefixer@*:
    dependencies:
      postcss: "*"
